/** The established 24 skate graphics stay on the fridge. The new 15 band graphics
 * start in the wooden drawer, ready to peel out and place. All retain independent
 * alpha-aware meshes and silver backs. See STICKER-CREDITS.md for provenance.
 */
export const CATALOG_VERSION = "drawer-bands-v4";
export const CATALOG = [
  {
    id: "pat-duffy",
    name: "Pat Duffy",
    category: "graphics",
    texture: "sticker-pat-duffy.webp",
    width: 0.6011,
    height: 1.02,
    u: -0.59,
    v: 1.5,
    angle: -7,
    surface: "front",
    seed: 86,
  },
  {
    id: "santa-cruz",
    name: "Santa Cruz",
    category: "logos",
    texture: "sticker-santa-cruz.webp",
    width: 1.04,
    height: 0.9826,
    u: 0.56,
    v: 1.52,
    angle: 8,
    surface: "front",
    seed: 117,
  },
  {
    id: "creature",
    name: "Creature",
    category: "logos",
    texture: "sticker-creature.webp",
    width: 1.53,
    height: 0.7451,
    u: 0.25,
    v: 0.62,
    angle: 6,
    surface: "front",
    seed: 148,
  },
  {
    id: "speed-face",
    name: "Speed Face",
    category: "graphics",
    texture: "sticker-speed-face.webp",
    width: 0.5163,
    height: 0.62,
    u: -0.45,
    v: -0.03,
    angle: -12,
    surface: "front",
    seed: 179,
  },
  {
    id: "spitfire",
    name: "Spitfire",
    category: "graphics",
    texture: "sticker-spitfire.webp",
    width: 0.8357,
    height: 1.1,
    u: 0.63,
    v: -0.24,
    angle: -6,
    surface: "front",
    seed: 210,
  },
  {
    id: "toy-machine",
    name: "Toy Machine",
    category: "graphics",
    texture: "sticker-toy-machine.webp",
    width: 1.07,
    height: 0.997,
    u: -0.6,
    v: -0.76,
    angle: 7,
    surface: "front",
    seed: 241,
  },
  {
    id: "vans",
    name: "Vans",
    category: "logos",
    texture: "sticker-vans.webp",
    width: 1.2,
    height: 0.5844,
    u: 0.58,
    v: -1.15,
    angle: -9,
    surface: "front",
    seed: 272,
  },
  {
    id: "alien-workshop",
    name: "Alien Workshop",
    category: "graphics",
    texture: "sticker-alien-workshop.webp",
    width: 0.7971,
    height: 0.93,
    u: -0.84,
    v: -1.95,
    angle: -5,
    surface: "front",
    seed: 303,
  },
  {
    id: "journeys",
    name: "Journeys",
    category: "graphics",
    texture: "sticker-journeys.webp",
    width: 0.7754,
    height: 0.87,
    u: 0.04,
    v: -1.96,
    angle: 6,
    surface: "front",
    seed: 334,
  },
  {
    id: "rainbow-melt",
    name: "Rainbow Melt",
    category: "graphics",
    texture: "sticker-rainbow-melt.webp",
    width: 0.5984,
    height: 0.96,
    u: 0.99,
    v: -1.97,
    angle: -5,
    surface: "front",
    seed: 365,
  },
  {
    id: "zumiez",
    name: "Zumiez",
    category: "logos",
    texture: "sticker-zumiez.webp",
    width: 0.7568,
    height: 1.05,
    u: 0.2,
    v: 1.57,
    angle: 4,
    surface: "right",
    seed: 396,
  },
  {
    id: "187-killer-pads",
    name: "187 Killer Pads",
    category: "logos",
    texture: "sticker-187-killer-pads.webp",
    width: 1.13,
    height: 0.6622,
    u: -0.12,
    v: 0.62,
    angle: -6,
    surface: "right",
    seed: 427,
  },
  {
    id: "bullet",
    name: "Bullet",
    category: "logos",
    texture: "sticker-bullet.webp",
    width: 1.1,
    height: 0.9714,
    u: 0.09,
    v: -0.49,
    angle: 8,
    surface: "right",
    seed: 458,
  },
  {
    id: "independent",
    name: "Independent",
    category: "logos",
    texture: "sticker-independent.webp",
    width: 0.83,
    height: 0.83,
    u: -0.13,
    v: -1.8,
    angle: -7,
    surface: "right",
    seed: 489,
  },
  {
    id: "black-label",
    name: "Black Label",
    category: "graphics",
    texture: "sticker-black-label.webp",
    width: 0.9698,
    height: 0.6518,
    u: -0.03,
    v: 2.1024,
    angle: -7,
    surface: "left",
    seed: 801,
    edition: "mid90s-expansion",
  },
  {
    id: "alien-workshop-spectrum",
    name: "Alien Workshop · Spectrum",
    category: "logos",
    texture: "sticker-alien-workshop-spectrum.webp",
    width: 1.0714,
    height: 0.5879,
    u: 0.12,
    v: 1.3613,
    angle: 4,
    surface: "left",
    seed: 832,
    edition: "mid90s-expansion",
  },
  {
    id: "antihero",
    name: "Anti Hero",
    category: "graphics",
    texture: "sticker-antihero.webp",
    width: 1.2007,
    height: 0.5126,
    u: -0.07,
    v: 0.695,
    angle: -5,
    surface: "left",
    seed: 863,
    edition: "mid90s-expansion",
  },
  {
    id: "dvs",
    name: "DVS",
    category: "logos",
    texture: "sticker-dvs.webp",
    width: 1.016,
    height: 0.4734,
    u: 0.08,
    v: 0.0793,
    angle: 5,
    surface: "left",
    seed: 894,
    edition: "mid90s-expansion",
  },
  {
    id: "independent-crossbar",
    name: "Independent · Crossbar",
    category: "logos",
    texture: "sticker-independent-crossbar.webp",
    width: 1.0806,
    height: 0.5228,
    u: -0.1,
    v: -0.5362,
    angle: -5,
    surface: "left",
    seed: 925,
    edition: "mid90s-expansion",
  },
  {
    id: "plan-b",
    name: "Plan B",
    category: "logos",
    texture: "sticker-plan-b.webp",
    width: 1.0437,
    height: 0.3829,
    u: 0.11,
    v: -1.0902,
    angle: 3,
    surface: "left",
    seed: 956,
    edition: "mid90s-expansion",
  },
  {
    id: "element",
    name: "Element",
    category: "logos",
    texture: "sticker-element.webp",
    width: 0.6188,
    height: 0.6229,
    u: -0.16,
    v: -1.6739,
    angle: -5,
    surface: "left",
    seed: 987,
    edition: "mid90s-expansion",
  },
  {
    id: "krooked",
    name: "Krooked",
    category: "logos",
    texture: "sticker-krooked.webp",
    width: 1.0899,
    height: 0.4459,
    u: 0.06,
    v: -2.2621,
    angle: 0,
    surface: "left",
    seed: 1018,
    edition: "mid90s-expansion",
  },
  {
    id: "krux",
    name: "Krux",
    category: "logos",
    texture: "sticker-krux.webp",
    width: 1.15,
    height: 0.2371,
    u: -0.02,
    v: 2.31,
    angle: -4,
    surface: "right",
    seed: 1346,
    edition: "mid90s-expansion",
  },
  {
    id: "es",
    name: "éS",
    category: "logos",
    texture: "sticker-es.webp",
    width: 0.4,
    height: 0.522,
    u: -0.61,
    v: 1.52,
    angle: 2,
    surface: "right",
    seed: 1353,
    edition: "mid90s-expansion",
  },
  {
    id: "band-weezer",
    name: "Weezer",
    category: "bands",
    texture: "sticker-band-weezer.webp",
    width: 1.04,
    height: 0.5639,
    u: 0.18,
    v: 0.3,
    angle: -5,
    surface: "front",
    seed: 2400,
    edition: "90s-bands",
    placed: false,
  },
  {
    id: "band-soundgarden",
    name: "Soundgarden",
    category: "bands",
    texture: "sticker-band-soundgarden.webp",
    width: 1.3,
    height: 0.4031,
    u: 0.18,
    v: 0.3,
    angle: 4,
    surface: "front",
    seed: 2447,
    edition: "90s-bands",
    placed: false,
  },
  {
    id: "band-alice-in-chains",
    name: "Alice in Chains",
    category: "bands",
    texture: "sticker-band-alice-in-chains.webp",
    width: 1.22,
    height: 0.4456,
    u: 0.18,
    v: 0.3,
    angle: -3,
    surface: "front",
    seed: 2494,
    edition: "90s-bands",
    placed: false,
  },
  {
    id: "band-foo-fighters",
    name: "Foo Fighters",
    category: "bands",
    texture: "sticker-band-foo-fighters.webp",
    width: 1.09,
    height: 0.6972,
    u: 0.18,
    v: 0.3,
    angle: 6,
    surface: "front",
    seed: 2541,
    edition: "90s-bands",
    placed: false,
  },
  {
    id: "band-red-hot-chili-peppers",
    name: "Red Hot Chili Peppers",
    category: "bands",
    texture: "sticker-band-red-hot-chili-peppers.webp",
    width: 0.94,
    height: 0.9293,
    u: 0.18,
    v: 0.3,
    angle: -5,
    surface: "front",
    seed: 2588,
    edition: "90s-bands",
    placed: false,
  },
  {
    id: "band-radiohead",
    name: "Radiohead",
    category: "bands",
    texture: "sticker-band-radiohead.webp",
    width: 1.0,
    height: 0.7532,
    u: 0.18,
    v: 0.3,
    angle: 4,
    surface: "front",
    seed: 2635,
    edition: "90s-bands",
    placed: false,
  },
  {
    id: "band-smashing-pumpkins",
    name: "Smashing Pumpkins",
    category: "bands",
    texture: "sticker-band-smashing-pumpkins.webp",
    width: 1.0,
    height: 0.9594,
    u: 0.18,
    v: 0.3,
    angle: -3,
    surface: "front",
    seed: 2682,
    edition: "90s-bands",
    placed: false,
  },
  {
    id: "band-stone-temple-pilots",
    name: "Stone Temple Pilots",
    category: "bands",
    texture: "sticker-band-stone-temple-pilots.webp",
    width: 1.0,
    height: 0.6916,
    u: 0.18,
    v: 0.3,
    angle: 6,
    surface: "front",
    seed: 2729,
    edition: "90s-bands",
    placed: false,
  },
  {
    id: "band-oasis",
    name: "Oasis",
    category: "bands",
    texture: "sticker-band-oasis.webp",
    width: 1.08,
    height: 0.5435,
    u: 0.18,
    v: 0.3,
    angle: -5,
    surface: "front",
    seed: 2776,
    edition: "90s-bands",
    placed: false,
  },
  {
    id: "band-rage-against-the-machine",
    name: "Rage Against the Machine",
    category: "bands",
    texture: "sticker-band-rage-against-the-machine.webp",
    width: 0.94,
    height: 0.7706,
    u: 0.18,
    v: 0.3,
    angle: 4,
    surface: "front",
    seed: 2823,
    edition: "90s-bands",
    placed: false,
  },
  {
    id: "band-nirvana",
    name: "Nirvana",
    category: "bands",
    texture: "sticker-band-nirvana.webp",
    width: 0.87,
    height: 1.0326,
    u: 0.18,
    v: 0.3,
    angle: -3,
    surface: "front",
    seed: 2870,
    edition: "90s-bands",
    placed: false,
  },
  {
    id: "band-the-offspring",
    name: "The Offspring",
    category: "bands",
    texture: "sticker-band-the-offspring.webp",
    width: 1.26,
    height: 0.3293,
    u: 0.18,
    v: 0.3,
    angle: 6,
    surface: "front",
    seed: 2917,
    edition: "90s-bands",
    placed: false,
  },
  {
    id: "band-pearl-jam",
    name: "Pearl Jam",
    category: "bands",
    texture: "sticker-band-pearl-jam.webp",
    width: 1.19,
    height: 0.4231,
    u: 0.18,
    v: 0.3,
    angle: -5,
    surface: "front",
    seed: 2964,
    edition: "90s-bands",
    placed: false,
  },
  {
    id: "band-rem",
    name: "R.E.M.",
    category: "bands",
    texture: "sticker-band-rem.webp",
    width: 1.06,
    height: 0.487,
    u: 0.18,
    v: 0.3,
    angle: 4,
    surface: "front",
    seed: 3011,
    edition: "90s-bands",
    placed: false,
  },
  {
    id: "band-nine-inch-nails",
    name: "Nine Inch Nails",
    category: "bands",
    texture: "sticker-band-nine-inch-nails.webp",
    width: 1.12,
    height: 0.4764,
    u: 0.18,
    v: 0.3,
    angle: -3,
    surface: "front",
    seed: 3058,
    edition: "90s-bands",
    placed: false,
  },
];
